### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Gast9ra/uniq#1]
0. Нет тестов для всего, кроме разбора аргументов
1. У вас странно организован вывод. В частности, вам приходится писать такой код:
    ```java
            if (!argPosition.isO()) {
                for (int i = 0; i < result.size(); i++) {
                    System.out.println(result.get(i));
                }
            }else{
                fileDo.writeLine(argPosition.getOutput(),result);
            }
    ```
Лучше сделать метод `writeLines`, который записывает список строк в `PrintWriter` или `PrintStream`, отделив код создания `PrintWriter`'а для `System.out` и для файла.
2. При записи в файл вы делаете много лишних вещей:
     - `if (!file.exists()) file.createNewFile()` - файл и так создастся при создании `PrintWriter`'а
     - `file.getAbsoluteFile()` - зачем?
3. Класс `FileWork` не хранит никаких полей. Можно, например, хранить в нём входной и выходной поток и вызывать методы, не передавая имя файла и потоки. 
4. Подумайте, можно ли делать обработку "на лету", т. е. без промежуточного списка строк. У меня есть ощущение, что алгоритм в методе `command` это позволяет с незначительными модификациями. Тогда методы работы со списком строк вообще не нужны.
5. Есть некоторые косяки в форматировании кода, например в методе `comparison`.

**Comment by gagarski** [comment]
1. Замечание 1 вы явно поняли неправильно, логика записи списка строк в файл и в `System.out` дублируется. Можно сделать общий код, который пишет в `PrintWriter`. В зависимости от аргументов можно создать `PrintWriter` для файла, либо для `System.out` и передать его в функцию записи
2. Замечание #3 всё ещё актуально.

**Comment by gagarski** [comment]
3. Один из тестов падает при запуске:
```

java.lang.IllegalArgumentException: not valid name

	at com.packet.Flag.<init>(Flag.java:54)
	at test.flagTest(test.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:316)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:114)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.lambda$invokeTestMethod$6(MethodTestDescriptor.java:171)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.invokeTestMethod(MethodTestDescriptor.java:168)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:115)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$1(HierarchicalTestExecutor.java:81)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$1(HierarchicalTestExecutor.java:91)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$1(HierarchicalTestExecutor.java:91)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:87)
	at org.junit.platform.launcher.Launcher.execute(Launcher.java:93)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:61)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```
Скорее всего, следует вынести проверку на возможность чтения файла из разбора командной строки.
